version: '3.8'

services:
  server:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./src:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    links:
      - php
  php:
    build:
      context: .
      dockerfile: dockerfiles/php8.1.dockerfile
    volumes:
      - "./src:/var/www/html"
    extra_hosts:
      - "db.local:127.0.0.1"


    
